config/routes.rb
Rails.application.routes.draw do
  resources :lists

  resources :users, only: [:none] do
    resources :password_resets, only: [:edit, :update]
  end
  resources :password_resets, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get "/user/profile" => "users#profile"

  get '/user/lists' => "lists#user_lists"

  root 'session#new'

end

app/models/list.rb
class List < ActiveRecord::Base
	validates :user_id, :title, presence: true
	
	belongs_to :user
end

app/models/password_reset.rb
class PasswordReset < ActiveRecord::Base
  belongs_to :user
  before_create :generate_unique_token
  delegate :email, to: :user, allow_nil: true

  def to_param
    token
  end

  private

  def generate_unique_token
    self.token = generate_token
    while PasswordReset.exists?(token: self.token)
      self.token = generate_token
    end
  end

  def generate_token
    SecureRandom.hex(20).encode('UTF-8')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, :first_name, :last_name, presence: true

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  before_action :require_login, :set_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 
  def require_login
    unless signed_in?
      flash[:error] = "You must log in to access this section"
      redirect_to new_session_url # halts request cycle
    end
  end

  def set_user
  	@user = User.find(current_user.id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def user_lists
    @lists = List.where("user_id = ?", @user.id)
  end
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.where("public = ?", "true")
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    puts @user.id
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    puts list_params
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      puts "the params are: #{params}"
      params[:list][:user_id] = @user.id
      params.require(:list).permit(:title, :description, :public, :user_id)
    end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :edit, :update]
  skip_before_action :set_user, only: [:new, :create, :edit, :update]

  def new
    @password_reset = PasswordReset.new
  end

  def create
    user = User.find_by(email: params[:password_reset][:email])
    if user
      password_reset = PasswordReset.create(user: user)
      PasswordResetMailer.change_password(password_reset).deliver # NOTE: You'll want to delay this
    end
  end

  def edit
    @password_reset = PasswordReset.find_by!(token: params[:id], user_id: params[:user_id])
    @user = @password_reset.user
  end

  def update
    @password_reset = PasswordReset.find_by!(token: params[:id], user_id: params[:user_id])
    @user = @password_reset.user

    reset_password(@user, params[:password_reset][:password])

    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  skip_before_action :set_user, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to "/user/profile"
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  skip_before_action :set_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to '/user/profile'
    else
      render :new
    end
  end

  def profile
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadingAid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= @list.user_id %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :public? %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= list.public %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>public:</strong>
  <%= @list.public %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/user_lists.html.erb
<h1>Your lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= list.public %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/password_resets/create.html.erb
<div class="password-reset">
  <p>You will receive an email within the next few minutes. It contains instructions for changing your password.</p>
</div>

app/views/password_resets/edit.html.erb
<div class="password-reset">
  <h2>Change your password</h2>

  <p>Your password has been reset. Choose a new password below.</p>

  <%= form_for [@user, @password_reset] do |form| %>
    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit 'Update Password' %>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="password-reset">
  <h2>Reset your password</h2>

  <p>To be emailed a link to reset your password, please enter your email address.</p>

  <%= form_for @password_reset do |form| %>
    <div class="text-field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="submit-field">
      <%= form.submit 'Reset Password' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/profile.html.erb
<h1> <%= @user.first_name %> </h1>

<%= link_to "Add a List", new_list_path %>
<%=
   link_to_if(@user.lists.length != 0, "My Lists", { controller: "lists", action: "user_lists" }) do |name|
     link_to("Start!", { controller: "lists", action: "new" })
   end
%>
<%= link_to "Public Lists", lists_path %>